[2024-02-26 15:32:03] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:08] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:13] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:13] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 9c932476cf018f45 127.0.0.1:62453 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:32:13] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn 9c932476cf018f45 127.0.0.1:20132 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:32:18] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:23] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:28] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:33] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:38] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:43] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:45] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 9c932476cf018f45 127.0.0.1:62595 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:32:45] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn static dial conn 9c932476cf018f45 127.0.0.1:20132 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:32:48] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:49] [warning] blockChain.go:379 p3Chain/core/eles.(*BlockChain).CommitBlock Current NodeID:9c932476cf018f45b243ffbef8c88c5db9aff40c6bd58436de58aeeaacf2065e2cd7e0a72cea9d2cf9852f72016f9d7021abc37d2d89ddd1052b25b70a3411a1 commit Block into LevelDB

[2024-02-26 15:32:50] [warning] synchronization.go:240 p3Chain/blockSync.(*SyncProtocal).handleMsg Block synchronization: The number (30) of blocks requested by the remote node, and the actual number of blocks returned is (1) and currentHeight (0)

[2024-02-26 15:32:50] [warning] synchronization.go:240 p3Chain/blockSync.(*SyncProtocal).handleMsg Block synchronization: The number (30) of blocks requested by the remote node, and the actual number of blocks returned is (1) and currentHeight (0)

[2024-02-26 15:32:53] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:58] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
