[2024-02-26 15:33:03] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:33:08] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:33:13] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:33:15] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 9c932476cf018f45 127.0.0.1:62754 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:33:15] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn static dial conn 9c932476cf018f45 127.0.0.1:20132 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:33:18] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:33:23] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:33:28] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:33:33] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:33:38] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:33:43] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:33:47] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 9c932476cf018f45 127.0.0.1:62930 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:33:47] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn static dial conn 9c932476cf018f45 127.0.0.1:20132 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:33:48] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:33:53] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:33:58] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
