[2024-02-26 15:35:01] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:35:06] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:35:08] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 352865d3401a4b5b 127.0.0.1:63302 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:35:08] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn static dial conn 352865d3401a4b5b 127.0.0.1:20130 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:35:11] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:35:16] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
