[2024-02-26 15:32:04] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:09] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:14] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn ea52714e4fd1a687 127.0.0.1:62462 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:32:14] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn static dial conn ea52714e4fd1a687 127.0.0.1:20136 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:32:14] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:19] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:24] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:29] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:34] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:39] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:44] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:44] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn ea52714e4fd1a687 127.0.0.1:62592 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:32:44] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn ea52714e4fd1a687 127.0.0.1:20136 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:32:49] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:54] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:59] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
