[2024-03-28 17:51:50] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn e854f680f9662f50 127.0.0.1:58230 failed checkpoint posthandshake: Connected to self
[2024-03-28 17:51:50] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn e854f680f9662f50 127.0.0.1:20136 failed checkpoint posthandshake: Connected to self
