[2024-02-26 15:32:04] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:09] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:14] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn static dial conn aa9452e8ff26a194 127.0.0.1:20133 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:32:14] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn aa9452e8ff26a194 127.0.0.1:62458 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:32:14] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:19] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:24] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:29] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:34] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:39] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:44] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:44] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn aa9452e8ff26a194 127.0.0.1:62590 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:32:44] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn aa9452e8ff26a194 127.0.0.1:20133 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:32:49] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:54] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:59] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
