[2024-02-26 15:32:04] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:09] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:11] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 1b469003b449ae80 127.0.0.1:62404 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:32:11] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn static dial conn 1b469003b449ae80 127.0.0.1:20131 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:32:14] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:19] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:24] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:29] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:34] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:39] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:41] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn 1b469003b449ae80 127.0.0.1:62582 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:32:41] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn static dial conn 1b469003b449ae80 127.0.0.1:20131 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:32:44] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:49] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:49] [warning] blockChain.go:379 p3Chain/core/eles.(*BlockChain).CommitBlock Current NodeID:1b469003b449ae80da03061f2a4fa7306c4cf364ebacb3d67a65417735238ea6a164afdef5a43ceac85f80f0b18729fda57ba01134f470952945093dc149cd23 commit Block into LevelDB

[2024-02-26 15:32:50] [warning] synchronization.go:240 p3Chain/blockSync.(*SyncProtocal).handleMsg Block synchronization: The number (30) of blocks requested by the remote node, and the actual number of blocks returned is (1) and currentHeight (0)

[2024-02-26 15:32:50] [warning] synchronization.go:240 p3Chain/blockSync.(*SyncProtocal).handleMsg Block synchronization: The number (30) of blocks requested by the remote node, and the actual number of blocks returned is (1) and currentHeight (0)

[2024-02-26 15:32:54] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:32:59] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (2) nodes unable to establish P2P communication due to exceptions
