[2024-02-26 15:33:04] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:33:09] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:33:14] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:33:16] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn a40fd9471091bc7f 127.0.0.1:62759 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:33:16] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn static dial conn a40fd9471091bc7f 127.0.0.1:20135 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:33:19] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:33:24] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:33:29] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:33:34] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:33:39] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:33:44] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:33:46] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn inbound conn a40fd9471091bc7f 127.0.0.1:62920 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:33:46] [warning] server.go:631 p3Chain/p2p/server.(*Server).setupConn dyn dial conn a40fd9471091bc7f 127.0.0.1:20135 failed checkpoint posthandshake: Connected to self
[2024-02-26 15:33:49] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:33:54] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
[2024-02-26 15:33:59] [warning] separator.go:293 p3Chain/core/separator.(*Separator).DoBind Separator Construct: (1) nodes unable to establish P2P communication due to exceptions
